---
- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no
  sudo: yes

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  sudo: yes

- name: Update default Apache site
  sudo: yes

  # 下記のように置換
  # DocumentRoot /var/www/html
  #  →DocumentRoot /var/www/wordpress
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache
  sudo: yes

- name: Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php
  sudo: yes

- name: Update WordPress config file
  lineinfile:
    dest=/var/www/wordpress/wp-config.php
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    # item.regexp には、リストのアイテムのうち、regexp key の value を使い、
    # item.line には、リストのアイテムのうち、line key の value を使う
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\)", 'line': "define('DB_NAME', '{{ wp_mysql_db}}');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\)", 'line': "define('DB_USER', '{{ wp_mysql_user}}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\)", 'line': "define('DB_PASSWORD', '{{ wp_mysql_password}}');"}
  sudo: yes
