1.script を転送
# 指令を出す側のシステム内にある ローカル script をリモートのシステムにコピー

2.リモートシステムにて、スクリプト実行

-
  name: Play 1
  hosts: localhost
  tasks:
    - name: Run a script on remote server
      script: /some/local/script.sh -arg1 -arg2

# Example from Ansible Playbooks
- script: /some/local/script.sh --some-arguments 1234

# Run a script that creates a file, but only if the file is not yet created
- script: /some/local/create_file.sh --some-arguments 1234
  args:
    creates: /the/created/file.txt

# Run a script that removes a file, but only if the file is not yet removed
- script: /some/local/remove_file.sh --some-arguments 1234
  args:
    removes: /the/removed/file.txt
