▼ ファイルを動的修正可能にする
-------------------------------------------------
// configuration を template と呼んでる
// 例えば、httpd.conf のポートナンバーを jinja で置換した上で、
// ソースから 宛先のディレクトリへ渡すことができる

  // - hosts: web_portal
  //   tasks:
  //   ...
      - name: Copy template file
      // ソース・ファイル内から 変数を読み取って、fact の内容と置換したりした上で
      // 宛先にコピーする
        template: src=current.html.j2 dest=/var/www/html

-------------------------------------------------


▼ jinja ファイル
-------------------------------------------------
Python のテンプレートエンジン

// This is my current file -
変数を使用
// My hostname is - {{ ansible_hostname }}
-------------------------------------------------
