---
Resources:
########## VPC ##########
  TestVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: CFnVpc
      EnableDnsSupport: 'True'
      EnableDnsHostnames: 'True'
########## Subnet ##########
  TestFrontPublicA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref TestVpc
      Tags:
      - Key: Name
        Value: Front Public Subnet


  TestPrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1
      CidrBlock: 10.0.3.0/24
      VpcId: !Ref TestVpc
      Tags:
      - Key: Name
        Value: Private Subnet for instances


  TestDbSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1
      CidrBlock: 10.0.5.0/24
      VpcId: !Ref TestVpc
      Tags:
      - Key: Name
        Value: Private Subnet for Db







########## Internet Gateway ##########
  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: InternetGateway01
  MyIgwVpcAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: MyInternetGateway
      VpcId:
        Ref: TestVpc
