Parameters:
  EnvironmentName:
    Description: Environment Name
    Type: String
    # 本パラメータの値は二択
    AllowedValues: [development, production]
    ConstraintDescription: must be development or production

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      # EnvironmentToInstanceType マッピングの、EnvironmentName の、instanceType →例 t2.small
      InstanceType: !FindInMap [EnvironmentToInstanceType, !Ref 'EnvironmentName', instanceType]
      # Note we use the pseudo parameter AWS::Region
      ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', HVM64]

Mappings:
  EnvironmentToInstanceType:
    development:
      instanceType: t2.micro
    # we want a bigger instance type in production
    production:
      instanceType: t2.micro

# enumみたく使える
# dev vs prod, Region, AZ, AWS アカウント, AMI タイプ
#
# Map した値の参照
# !FindInMap [マップ名、トップレベルKey, セカンドレベルKey]
# InstanceType: !FindInMap [EnvironmentToInstanceType, !Ref 'EnvironmentName', instanceType]


# ▼ Parameter vs Mappings
# -------------------------------------------------
# Parameter →更新することで可変可能な値
# Mappings →事前に決まっている値。不可変
# -------------------------------------------------

  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-c2680fa4
    us-west-2:
      HVM64: ami-c2680fa4
    us-west-1:
      HVM64: ami-c2680fa4
    eu-west-1:
      HVM64: ami-c2680fa4
    eu-central-1:
      HVM64: ami-c2680fa4
    ap-northeast-1:
      HVM64: ami-c2680fa4
    ap-northeast-2:
      HVM64: ami-c2680fa4
    ap-southeast-1:
      HVM64: ami-c2680fa4
    ap-southeast-2:
      HVM64: ami-c2680fa4
    ap-south-1:
      HVM64: ami-c2680fa4
    us-east-2:
      HVM64: ami-c2680fa4
    sa-east-1:
      HVM64: ami-c2680fa4
    cn-north-1:
      HVM64: ami-c2680fa4
